{ self, inputs, ... }:
{
    # NixOS feature module: builds the AzerothCore (WotLK) Playerbot fork
    # with mod-playerbots compiled in, wires up MySQL, generates the
    # server config files and provides systemd units.
    #
    # Usage from a host configuration:
    #   imports = [ self.nixosModules.azerothcore ];
    #   services.azerothcore.enable = true;
    flake.nixosModules.azerothcore = { config, lib, pkgs, ... }:
    let
        cfg = config.services.azerothcore;

        # Connection strings shared by all three servers + the playerbots
        # module:  host;port;user;password;database
        dbInfo = db: "127.0.0.1;3306;${cfg.mysqlUser};${cfg.mysqlPassword};${db}";

        # key = value
        kv = k: v: "${k} = ${v}";

        # --------------------------------------------------------------
        # Merge the AzerothCore Playerbot fork with mod-playerbots the
        # same way the upstream quick-start does it:
        #   git clone mod-playerbots azerothcore-wotlk/modules/mod-playerbots
        # The fork's CMake auto-discovers modules/* (a directory that
        # contains a src/ subdir) and bakes the module list + config
        # list + SQL-update paths into the binaries. The result is a
        # store path that persists, so the runtime lookups below keep
        # working.
        #
        # Both inputs are source-only flake inputs (flake = false), so
        # `inputs.azerothcore` and `inputs.playerbots` are the source
        # tree paths themselves.
        # --------------------------------------------------------------
        mergedSource =
            if cfg.enablePlayerbots then
                pkgs.stdenvNoCC.mkDerivation {
                    pname = "azerothcore-wotlk-with-playerbots";
                    version = "17.0.0";
                    dontUnpack = true;
                    buildPhase = ''
                        cp -r ${inputs.azerothcore} merged
                        mkdir -p merged/modules
                        cp -r ${inputs.playerbots} merged/modules/mod-playerbots
                        mv merged $out
                    '';
                }
            else
                inputs.azerothcore;

        # --------------------------------------------------------------
        # Config files.
        #
        # Each server reads <prefix>/etc/<name>.conf (CONF_DIR is baked
        # in as <prefix>/etc by src/cmake/platform/unix/settings.cmake),
        # and the worldserver additionally reads
        # <prefix>/etc/modules/<module>.conf for each compiled-in module.
        #
        # IMPORTANT: AzerothCore's Config.cpp keeps the *first*
        # occurrence of a key and skips later duplicates
        # (Config::ParseFile -> IsDuplicateOption). The shipped
        # *.conf.dist files already define keys such as
        # LoginDatabaseInfo / RealmServerPort / WorldServerPort /
        # DataDir / SourceDirectory, so we cannot simply append our
        # values. Instead we generate a complete .conf that contains
        # only the keys we care about; the rest of the server behaviour
        # falls back to the compiled-in defaults.
        #
        # SourceDirectory points at the source tree that was compiled
        # into the package (the store path of `mergedSource`). The
        # runtime SQL base/updates lookups (worldserver auth/world/
        # characters updaters, the dbimport tool, and the playerbots
        # module's own DB updater) all resolve relative to this path, so
        # it must persist in the store — which it does, because the
        # systemd units reference the package and thus GC-protect it.
        # --------------------------------------------------------------
        authserverConf = pkgs.writeText "authserver.conf" ''
            # --- generated by nixos-dendritic-system (azerothcore) ---
            ${kv "RealmServerPort" (toString cfg.authPort)}
            ${kv "LoginDatabaseInfo" (dbInfo "acore_auth")}
            ${kv "LogsDir" "/var/lib/azerothcore/logs"}
            ${kv "TempDir" "/var/lib/azerothcore"}
            ${kv "MySQLExecutable" "${pkgs.mysql84}/bin/mysql"}
            ${kv "SourceDirectory" mergedSource}
        '';

        worldserverConf = pkgs.writeText "worldserver.conf" ''
            # --- generated by nixos-dendritic-system (azerothcore) ---
            ${kv "DataDir" cfg.dataDir}
            ${kv "WorldServerPort" (toString cfg.worldPort)}
            ${kv "LoginDatabaseInfo" (dbInfo "acore_auth")}
            ${kv "WorldDatabaseInfo" (dbInfo "acore_world")}
            ${kv "CharacterDatabaseInfo" (dbInfo "acore_characters")}
            ${kv "LogsDir" "/var/lib/azerothcore/logs"}
            ${kv "TempDir" "/var/lib/azerothcore"}
            ${kv "MySQLExecutable" "${pkgs.mysql84}/bin/mysql"}
            ${kv "SourceDirectory" mergedSource}
            ${lib.concatStringsSep "\n" (lib.mapAttrsToList kv cfg.extraOverrides)}
            ${cfg.extraWorldConf}
        '';

        dbimportConf = pkgs.writeText "dbimport.conf" ''
            # --- generated by nixos-dendritic-system (azerothcore) ---
            ${kv "LoginDatabaseInfo" (dbInfo "acore_auth")}
            ${kv "WorldDatabaseInfo" (dbInfo "acore_world")}
            ${kv "CharacterDatabaseInfo" (dbInfo "acore_characters")}
            ${kv "LogsDir" "/var/lib/azerothcore/logs"}
            ${kv "TempDir" "/var/lib/azerothcore"}
            ${kv "MySQLExecutable" "${pkgs.mysql84}/bin/mysql"}
            ${kv "SourceDirectory" mergedSource}
        '';

        playerbotsConf = pkgs.writeText "playerbots.conf" ''
            # --- generated by nixos-dendritic-system (azerothcore) ---
            ${kv "PlayerbotsDatabaseInfo" (dbInfo "acore_playerbots")}
        '';

        # --------------------------------------------------------------
        # Build the servers.
        #
        # - src is a store path, so CMAKE_SOURCE_DIR (baked into
        #   revision.h as _SOURCE_DIRECTORY) is a persistent store path.
        # - APPS_BUILD=all builds authserver + worldserver.
        # - TOOLS_BUILD=db-only builds dbimport (its default is "none",
        #   which would otherwise skip the dbimport tool entirely).
        # - MODULES=static + SCRIPTS=static compile the playerbots module
        #   into the worldserver.
        # --------------------------------------------------------------
        azerothcorePkg =
            if cfg.enable then
                pkgs.stdenv.mkDerivation {
                    pname = "azerothcore-wotlk";
                    version = "17.0.0";

                    src = mergedSource;

                    nativeBuildInputs = [
                        pkgs.cmake
                        pkgs.ninja
                        # Provides mysql_config, which FindMySQL.cmake uses
                        # to locate the MySQL client headers/library.
                        pkgs.mysql84
                    ];

                    buildInputs = [
                        pkgs.boost
                        pkgs.openssl
                        pkgs.mysql84
                        pkgs.readline
                        pkgs.bzip2
                        pkgs.zlib
                    ];

                    # Build in-tree (read-only source is fine: CMake only
                    # writes to the build dir; WITHOUT_GIT avoids needing a
                    # .git directory, which store paths do not have).
                    cmakeFlags = [
                        # String-valued options (CACHE STRING in the core's
                        # conf/dist/config.cmake) are passed as plain -D
                        # strings; lib.cmakeBool only works for booleans.
                        "-DAPPS_BUILD=all"      # build authserver + worldserver
                        "-DTOOLS_BUILD=db-only" # build dbimport (default "none" skips it)
                        "-DSCRIPTS=static"
                        "-DMODULES=static"      # compile the playerbots module in
                        (lib.cmakeBool "BUILD_TESTING" false)
                        (lib.cmakeBool "WITHOUT_GIT" true)  # store paths have no .git
                        (lib.cmakeBool "USE_COREPCH" false)
                        (lib.cmakeBool "USE_SCRIPTPCH" false)
                    ];
                    cmakeBuildType = "RelWithDebInfo";

                    # Install the complete, operator-managed config files
                    # next to the binaries (CONF_DIR == <prefix>/etc).
                    postInstall = ''
                        install -Dm644 ${authserverConf} $out/etc/authserver.conf
                        install -Dm644 ${worldserverConf} $out/etc/worldserver.conf
                        install -Dm644 ${dbimportConf} $out/etc/dbimport.conf
                        ${lib.optionalString cfg.enablePlayerbots ''
                            install -Dm644 ${playerbotsConf} $out/etc/modules/playerbots.conf
                        ''}
                    '';
                }
            else null;
    in
    {
        options.services.azerothcore = {
            enable = lib.mkEnableOption "the AzerothCore (WotLK) server with mod-playerbots support";

            enablePlayerbots = lib.mkOption {
                type = lib.types.bool;
                default = true;
                description = ''
                    Compile in the mod-playerbots module. This flake fetches
                    the mod-playerbots/azerothcore-wotlk fork, which is
                    required for playerbots; vanilla AzerothCore will not
                    build the module.
                '';
            };

            dataDir = lib.mkOption {
                type = lib.types.path;
                default = "/var/lib/azerothcore/data";
                description = ''
                    Directory holding the WoW WotLK client data (dbc/,
                    maps/, vmaps/, mmaps/). Must be populated manually from
                    a legitimate game client install.
                '';
            };

            worldPort = lib.mkOption {
                type = lib.types.port;
                default = 8085;
                description = "TCP port the world server listens on.";
            };

            authPort = lib.mkOption {
                type = lib.types.port;
                default = 3724;
                description = "TCP port the auth server listens on.";
            };

            openFirewall = lib.mkOption {
                type = lib.types.bool;
                default = false;
                description = "Open the auth and world TCP ports on the NixOS firewall.";
            };

            extraOverrides = lib.mkOption {
                type = lib.types.attrsOf lib.types.str;
                default = { };
                description = "Extra worldserver.conf key/value overrides, e.g. { GM.StartLevel = \"50\"; }.";
            };

            extraWorldConf = lib.mkOption {
                type = lib.types.str;
                default = "";
                description = "Raw lines appended to the generated worldserver.conf.";
            };

            user = lib.mkOption {
                type = lib.types.str;
                default = "azerothcore";
                description = "System user the servers run as.";
            };

            mysqlUser = lib.mkOption {
                type = lib.types.str;
                default = "acore";
                description = "MySQL user the servers connect as.";
            };

            mysqlPassword = lib.mkOption {
                type = lib.types.str;
                default = "acore";
                description = "MySQL password for the database user. Change in production.";
            };
        };

        config = lib.mkIf cfg.enable {
            assertions = [{
                assertion = cfg.enablePlayerbots;
                message = "services.azerothcore.enablePlayerbots must stay true: this flake fetches the mod-playerbots fork of AzerothCore, and the playerbots module only builds against it.";
            }];

            # ----------------------------------------------------------
            # MySQL
            # ----------------------------------------------------------
            services.mysql = {
                enable = true;
                package = pkgs.mysql84;
                settings = {
                    bind-address = "127.0.0.1";
                    mysqld.max_connections = 300;
                };
                ensureDatabases = [
                    "acore_auth"
                    "acore_world"
                    "acore_characters"
                    "acore_playerbots"
                ];
                # nixpkgs creates the user from `name`/`password` and then
                # runs `creationStatement`; the AzerothCore servers connect
                # over TCP to 127.0.0.1, which reverse-resolves to
                # 'localhost', so grant to that host.
                ensureUsers = [{
                    name = cfg.mysqlUser;
                    password = cfg.mysqlPassword;
                    creationStatement = ''
                        GRANT ALL PRIVILEGES ON acore_auth.* TO '${cfg.mysqlUser}'@'localhost';
                        GRANT ALL PRIVILEGES ON acore_world.* TO '${cfg.mysqlUser}'@'localhost';
                        GRANT ALL PRIVILEGES ON acore_characters.* TO '${cfg.mysqlUser}'@'localhost';
                        GRANT ALL PRIVILEGES ON acore_playerbots.* TO '${cfg.mysqlUser}'@'localhost';
                    '';
                }];
            };

            # ----------------------------------------------------------
            # Runtime user + writable directories
            # ----------------------------------------------------------
            users.users.${cfg.user} = {
                isSystemUser = true;
                group = cfg.user;
                home = "/var/lib/azerothcore";
            };
            users.groups.${cfg.user} = { };

            systemd.tmpfiles.rules = [
                "d /var/lib/azerothcore 0750 ${cfg.user} ${cfg.user} - -"
                "d /var/lib/azerothcore/logs 0750 ${cfg.user} ${cfg.user} - -"
                "d /var/lib/azerothcore/data 0750 ${cfg.user} ${cfg.user} - -"
                "d /var/lib/azerothcore/data/dbc 0750 ${cfg.user} ${cfg.user} - -"
                "d /var/lib/azerothcore/data/maps 0750 ${cfg.user} ${cfg.user} - -"
                "d /var/lib/azerothcore/data/vmaps 0750 ${cfg.user} ${cfg.user} - -"
                "d /var/lib/azerothcore/data/mmaps 0750 ${cfg.user} ${cfg.user} - -"
            ];

            # ----------------------------------------------------------
            # Services
            # ----------------------------------------------------------
            systemd.services = {
                azerothcore-dbimport = {
                    description = "AzerothCore database import (auth/world/characters)";
                    wantedBy = [ "multi-user.target" ];
                    after = [ "network.target" "mysql.service" ];
                    wants = [ "mysql.service" ];
                    # Hash-based and idempotent — cheap to re-run every
                    # boot, keeps the DBs in sync with source updates.
                    # NOTE: dbimport only seeds Login/Character/World; the
                    # playerbots DB is created + populated by the
                    # worldserver (the mod-playerbots module runs its own
                    # DB updater during OnDatabasesLoading).
                    serviceConfig = {
                        Type = "oneshot";
                        User = cfg.user;
                        Environment = [
                            # Databases are pre-created by NixOS; never
                            # block on an interactive prompt.
                            "AC_DISABLE_INTERACTIVE=1"
                        ];
                    };
                    path = [ pkgs.bash pkgs.coreutils pkgs.mysql84 ];
                    script = ''
                        ${lib.getExe' azerothcorePkg "dbimport"}
                    '';
                };

                azerothcore-authserver = {
                    description = "AzerothCore auth server";
                    wantedBy = [ "multi-user.target" ];
                    after = [ "network.target" "mysql.service" "azerothcore-dbimport.service" ];
                    wants = [ "mysql.service" ];
                    restartIfChanged = true;
                    serviceConfig = {
                        User = cfg.user;
                        Environment = [ "AC_DISABLE_INTERACTIVE=1" ];
                        Restart = "on-failure";
                        RestartSec = "5";
                    };
                    path = [ pkgs.bash pkgs.coreutils pkgs.mysql84 ];
                    script = ''
                        ${lib.getExe' azerothcorePkg "authserver"}
                    '';
                };

                azerothcore-worldserver = {
                    description = "AzerothCore world server (WotLK, mod-playerbots)";
                    wantedBy = [ "multi-user.target" ];
                    after = [ "network.target" "mysql.service" "azerothcore-authserver.service" ];
                    wants = [ "mysql.service" ];
                    restartIfChanged = true;
                    serviceConfig = {
                        User = cfg.user;
                        # The WotLK worldserver opens thousands of
                        # map/DB handles.
                        LimitNOFILE = 16384;
                        Environment = [ "AC_DISABLE_INTERACTIVE=1" ];
                        Restart = "on-failure";
                        RestartSec = "10";
                        # First start populates the playerbots DB and
                        # loads all maps; allow a generous start timeout.
                        TimeoutStartSec = "600";
                    };
                    path = [ pkgs.bash pkgs.coreutils pkgs.mysql84 ];
                    script = ''
                        ${lib.getExe' azerothcorePkg "worldserver"}
                    '';
                };
            };

            networking.firewall = lib.mkIf cfg.openFirewall {
                allowedTCPPorts = [ cfg.authPort cfg.worldPort ];
            };

            environment.systemPackages = [
                pkgs.mysql84 # convenient for manual DB work
            ];
        };
    };
}
