# Config-value machinery for the AzerothCore module: the option type and
# rendering used to turn the `*Config` attribute-set options (core servers
# and module configFiles) into the flat "Key = Value" .conf files the
# servers read. Pure: depends only on `lib` (and `builtins`), never on the
# module's options or `pkgs`.
{ lib }:
let

    # ---------------------------------------------------------------------
    # Config value type + rendering (shared by core and module confs).
    #
    # AzerothCore's Config::ParseFile is *flat*: there are no nested
    # sections, and keys that contain a dot ("GM.StartLevel",
    # "CharacterCreating.Disabled.RaceMask", "Visibility.Distance.Continents")
    # are single literal key names. The conf options therefore mirror that
    # one-to-one: every key is a single literal attr name - quoted in Nix
    # when it contains a dot - and its value is a string or an integer.
    # Nested attribute sets are not used (they cannot be rendered to the
    # flat conf format and would be ambiguous for dotted keys).
    #   worldserverConfig."GM.StartLevel" = "50";
    #   -> GM.StartLevel = 50
    #
    # The type is a plain `attrsOf (string | integer)`. No custom element
    # type is needed: the module system merges the per-file options *per
    # key* - `attrsOf` decomposes each whole-attrset definition into its
    # individual keys and routes them through the standard priority-based,
    # last-wins merge. Combined with the per-key lib.mkDefault declarations
    # done in `config` below, a host overriding one key of a file keeps
    # every other default key intact.
    # ---------------------------------------------------------------------
    confValueType = lib.types.attrsOf (lib.types.either lib.types.str lib.types.int);

    # Render a key/value attrset into the "Key = Value" lines the servers
    # expect. Keys are emitted in a stable, sensible order (the
    # most-frequently-tuned ones first) with any unknown keys appended
    # alphabetically, so the generated file is predictable and diffs stay
    # readable when a host adds or overrides keys.
    confOrder = [
        "RealmServerPort"
        "WorldServerPort"
        "DataDir"
        "LoginDatabaseInfo"
        "WorldDatabaseInfo"
        "CharacterDatabaseInfo"
        "PlayerbotsDatabaseInfo"
        "LogsDir"
        "TempDir"
        "MySQLExecutable"
    ];
    orderedNames = attrs:
        let
            present = builtins.attrNames attrs;
            known = builtins.filter (k: builtins.elem k present) confOrder;
            unknown = builtins.sort builtins.lessThan
                (builtins.filter (k: !builtins.elem k confOrder) present);
        in
        known ++ unknown;
    renderConf = name: attrs:
        ''
            # --- generated by nixos-dendritic-system (azerothcore: ${name}) ---
            ${lib.concatStringsSep "\n" (lib.map (k: "${k} = ${toString attrs.${k}}") (orderedNames attrs))}
        '';
in
{
    inherit
        confValueType
        renderConf;
}
