# AzerothCore's config machinery: the option type for the `*Config`
# attribute-set options (core servers and module configFiles), the renderer
# that turns them into the flat "Key = Value" .conf files the servers read,
# and the default key/value sets of the three core conf files.
#
# Depends on `lib` (and `builtins`) plus, for the defaults, the
# host-derived values (cfg, dbInfo, logsDir, tmpDir, mysqlExe); it never
# depends on the module's options or `pkgs`.
{ lib, cfg, dbInfo, logsDir, tmpDir, mysqlExe }:
let

    # Config value type + rendering (shared by core and module confs).
    #
    # AzerothCore's Config::ParseFile is *flat*: there are no nested
    # sections, and keys that contain a dot ("GM.StartLevel",
    # "CharacterCreating.Disabled.RaceMask", "Visibility.Distance.Continents")
    # are single literal key names. The conf options therefore mirror that
    # one-to-one: every key is a single literal attr name - quoted in Nix
    # when it contains a dot - and its value is a string or an integer.
    # Nested attribute sets are not used (they cannot be rendered to the
    # flat conf format and would be ambiguous for dotted keys).
    #   worldserverConfig."GM.StartLevel" = "50";
    #   -> GM.StartLevel = 50
    #
    # The type is a plain `attrsOf (string | integer)`. No custom element
    # type is needed: the module system merges the per-file options *per
    # key* - `attrsOf` decomposes each whole-attrset definition into its
    # individual keys and routes them through the standard priority-based,
    # last-wins merge. Combined with the per-key lib.mkDefault declarations
    # done in `config` below, a host overriding one key of a file keeps
    # every other default key intact.
    # ---------------------------------------------------------------------
    confValueType = lib.types.attrsOf (lib.types.either lib.types.str lib.types.int);

    # Render a key/value attrset into the "Key = Value" lines the servers
    # expect. Keys are emitted in a stable, sensible order (the
    # most-frequently-tuned ones first) with any unknown keys appended
    # alphabetically, so the generated file is predictable and diffs stay
    # readable when a host adds or overrides keys.
    confOrder = [
        "RealmServerPort"
        "WorldServerPort"
        "DataDir"
        "LoginDatabaseInfo"
        "WorldDatabaseInfo"
        "CharacterDatabaseInfo"
        "PlayerbotsDatabaseInfo"
        "LogsDir"
        "TempDir"
        "MySQLExecutable"
    ];
    orderedNames = attrs:
        let
            present = builtins.attrNames attrs;
            known = builtins.filter (k: builtins.elem k present) confOrder;
            unknown = builtins.sort builtins.lessThan
                (builtins.filter (k: !builtins.elem k confOrder) present);
        in
        known ++ unknown;
    renderConf = name: attrs:
        ''
            # --- generated by nixos-dendritic-system (azerothcore: ${name}) ---
            ${lib.concatStringsSep "\n" (lib.map (k: "${k} = ${toString attrs.${k}}") (orderedNames attrs))}
        '';

    # ---------------------------------------------------------------------
    # Default key/value pairs of AzerothCore's three core .conf files
    # (authserver, worldserver, dbimport), generated from the upstream
    # *.conf.dist files:
    #   src/server/apps/authserver/authserver.conf.dist
    #   src/server/apps/worldserver/worldserver.conf.dist
    #   src/tools/dbimport/dbimport.conf.dist
    #
    # Every conf key - including dotted ones such as
    # "Updates.EnableDatabases" - is a *flat* quoted attr name in the
    # original dist-file order; the renderer above writes them out
    # verbatim (AzerothCore's Config::ParseFile strips all double quotes
    # from values before using them).
    #
    # Values that depend on this host's configuration (ports, the
    # *DatabaseInfo connection strings, the log/temp dirs and the mysql
    # binary) are layered over the literals with `//` (right wins) at the
    # end of each attrset.
    #
    # SourceDirectory is deliberately absent: it is the one key whose value
    # is the package's own store path, supplied as the AC_SOURCE_DIRECTORY
    # environment variable by the systemd units (see default.nix).
    # ---------------------------------------------------------------------
    defaults =

        {

            authserver =
                # literal defaults from authserver.conf.dist
                {
                    "LogsDir" = "";
                    "MaxPingTime" = 30;
                    "RealmServerPort" = 3724;
                    "BindIP" = "0.0.0.0";
                    "EnableProxyProtocol" = 0;
                    "PidFile" = "";
                    "UseProcessors" = 0;
                    "ProcessPriority" = 0;
                    "RealmsStateUpdateDelay" = 20;
                    "WrongPass.MaxCount" = 0;
                    "WrongPass.BanTime" = 600;
                    "WrongPass.BanType" = 0;
                    "WrongPass.Logging" = 0;
                    "BanExpiryCheckInterval" = 60;
                    "StrictVersionCheck" = 0;
                    "MySQLExecutable" = "";
                    "TempDir" = "";
                    "IPLocationFile" = "";
                    "AllowLoggingIPAddressesInDatabase" = 1;
                    "LoginDatabaseInfo" = "127.0.0.1;3306;acore;acore;acore_auth";
                    "Database.Reconnect.Seconds" = 15;
                    "Database.Reconnect.Attempts" = 20;
                    "LoginDatabase.WorkerThreads" = 1;
                    "LoginDatabase.SynchThreads" = 1;
                    "TOTPMasterSecret" = "";
                    "Updates.EnableDatabases" = 1;
                    "Updates.AutoSetup" = 1;
                    "Updates.Redundancy" = 1;
                    "Updates.ArchivedRedundancy" = 0;
                    "Updates.AllowRehash" = 1;
                    "Updates.CleanDeadRefMaxCount" = 3;
                    "Appender.Console" = "1,5,0,\"1 9 3 6 5 8\"";
                    "Appender.Auth" = "2,5,0,Auth.log,w";
                    "Logger.root" = "4,Console Auth";
                    "Network.UseSocketActivation" = 0;
                }
                //
                # host-dependent values, override the dist literals above
                {
                    "RealmServerPort" = toString cfg.authPort;
                    "LoginDatabaseInfo" = dbInfo "acore_auth";
                    "LogsDir" = logsDir;
                    "TempDir" = tmpDir;
                    "MySQLExecutable" = mysqlExe;
                };

            worldserver =
                # literal defaults from worldserver.conf.dist
                {
                    "RealmID" = 1;
                    "WorldServerPort" = 8085;
                    "BindIP" = "0.0.0.0";
                    "LoginDatabaseInfo" = "127.0.0.1;3306;acore;acore;acore_auth";
                    "WorldDatabaseInfo" = "127.0.0.1;3306;acore;acore;acore_world";
                    "CharacterDatabaseInfo" = "127.0.0.1;3306;acore;acore;acore_characters";
                    "LoginDatabase.WorkerThreads" = 1;
                    "WorldDatabase.WorkerThreads" = 1;
                    "CharacterDatabase.WorkerThreads" = 1;
                    "LoginDatabase.SynchThreads" = 1;
                    "WorldDatabase.SynchThreads" = 1;
                    "CharacterDatabase.SynchThreads" = 1;
                    "MaxPingTime" = 30;
                    "Database.Reconnect.Seconds" = 15;
                    "Database.Reconnect.Attempts" = 20;
                    "DataDir" = ".";
                    "LogsDir" = "";
                    "TempDir" = "";
                    "CMakeCommand" = "";
                    "BuildDirectory" = "";
                    "MySQLExecutable" = "";
                    "PidFile" = "";
                    "Console.Enable" = 1;
                    "BeepAtStart" = 1;
                    "FlashAtStart" = 1;
                    "Updates.EnableDatabases" = 7;
                    "Updates.AutoSetup" = 1;
                    "Updates.Redundancy" = 1;
                    "Updates.ArchivedRedundancy" = 0;
                    "Updates.AllowRehash" = 1;
                    "Updates.CleanDeadRefMaxCount" = 3;
                    "Updates.ExceptionShutdownDelay" = 10000;
                    "Network.Threads" = 1;
                    "Network.OutKBuff" = -1;
                    "Network.OutUBuff" = 4096;
                    "Network.TcpNodelay" = 1;
                    "Network.EnableProxyProtocol" = 0;
                    "Network.UseSocketActivation" = 0;
                    "Ra.Enable" = 0;
                    "Ra.IP" = "0.0.0.0";
                    "Ra.Port" = 3443;
                    "Ra.MinLevel" = 3;
                    "SOAP.Enabled" = 0;
                    "SOAP.IP" = "127.0.0.1";
                    "SOAP.Port" = 7878;
                    "TOTPMasterSecret" = "";
                    "ThreadPool" = 2;
                    "UseProcessors" = 0;
                    "ProcessPriority" = 1;
                    "Compression" = 1;
                    "PacketLogFile" = "";
                    "LogDB.Opt.ClearInterval" = 10;
                    "LogDB.Opt.ClearTime" = 1209600;
                    "RecordUpdateTimeDiffInterval" = 300000;
                    "MinRecordUpdateTimeDiff" = 100;
                    "IPLocationFile" = "";
                    "AllowLoggingIPAddressesInDatabase" = 1;
                    "Allow.IP.Based.Action.Logging" = 0;
                    "LogSpamReports" = 1;
                    "ChatLog.Enable" = 0;
                    "Appender.Console" = "1,4,0,\"1 9 3 6 5 8\"";
                    "Appender.Server" = "2,5,0,Server.log,w";
                    "Appender.Playerbots" = "2,5,0,Playerbots.log,w";
                    "Appender.Errors" = "2,2,0,Errors.log,w";
                    "Logger.root" = "2,Console Server";
                    "Logger.diff" = "3,Console Server";
                    "Logger.mmaps" = "4,Server";
                    "Logger.scripts.hotswap" = "4,Console Server";
                    "Logger.server" = "4,Console Server";
                    "Logger.sql.sql" = "2,Console Errors";
                    "Logger.sql.updates" = "4,Console Server Errors";
                    "Logger.sql" = "4,Console Server";
                    "Logger.time.update" = "4,Console Server";
                    "Logger.module" = "4,Console Server";
                    "Logger.spells.scripts" = "2,Console Errors";
                    "Logger.playerbots" = "5,Console Playerbots";
                    "Log.Async.Enable" = 0;
                    "Metric.Enable" = 0;
                    "Metric.InfluxDB.Connection" = "127.0.0.1;8086;worldserver";
                    "Metric.InfluxDB.v2" = 0;
                    "Metric.InfluxDB.Org" = "";
                    "Metric.InfluxDB.Bucket" = "";
                    "Metric.InfluxDB.Token" = "";
                    "Metric.Interval" = 1;
                    "Metric.OverallStatusInterval" = 1;
                    "BirthdayTime" = 1222964635;
                    "PlayerLimit" = 1000;
                    "World.RealmAvailability" = 1;
                    "GameType" = 0;
                    "RealmZone" = 1;
                    "DBC.Locale" = 255;
                    "Expansion" = 2;
                    "ClientCacheVersion" = 0;
                    "SocketTimeOutTime" = 900000;
                    "SocketTimeOutTimeActive" = 60000;
                    "MaxOverspeedPings" = 2;
                    "DisconnectToleranceInterval" = 0;
                    "EnableLoginAfterDC" = 1;
                    "MinWorldUpdateTime" = 1;
                    "UpdateUptimeInterval" = 10;
                    "MaxCoreStuckTime" = 0;
                    "SaveRespawnTimeImmediately" = 1;
                    "Server.LoginInfo" = 0;
                    "ShowKickInWorld" = 0;
                    "ShowMuteInWorld" = 0;
                    "ShowBanInWorld" = 0;
                    "MaxWhoListReturns" = 49;
                    "PreventAFKLogout" = 0;
                    "PacketSpoof.BanMode" = 0;
                    "PacketSpoof.BanDuration" = 86400;
                    "Warden.Enabled" = 1;
                    "Warden.NumMemChecks" = 3;
                    "Warden.NumLuaChecks" = 1;
                    "Warden.NumOtherChecks" = 7;
                    "Warden.ClientResponseDelay" = 600;
                    "Warden.ClientCheckHoldOff" = 30;
                    "Warden.ClientCheckFailAction" = 0;
                    "Warden.BanDuration" = 86400;
                    "AutoBroadcast.On" = 0;
                    "AutoBroadcast.Center" = 0;
                    "AutoBroadcast.Timer" = 60000;
                    "AutoBroadcast.MinDisableLevel" = 0;
                    "Visibility.GroupMode" = 1;
                    "Visibility.Distance.Continents" = 100;
                    "Visibility.Distance.Instances" = 170;
                    "Visibility.Distance.BGArenas" = 250;
                    "Visibility.ObjectSparkles" = 1;
                    "Visibility.ObjectQuestMarkers" = 1;
                    "MapUpdateInterval" = 10;
                    "MapUpdate.Threads" = 1;
                    "MoveMaps.Enable" = 1;
                    "vmap.enableLOS" = 1;
                    "vmap.enableHeight" = 1;
                    "vmap.petLOS" = 1;
                    "vmap.BlizzlikePvPLOS" = 1;
                    "vmap.BlizzlikeLOSInOpenWorld" = 1;
                    "vmap.enableIndoorCheck" = 1;
                    "DetectPosCollision" = 1;
                    "CheckGameObjectLoS" = 1;
                    "PreloadAllNonInstancedMapGrids" = 0;
                    "DontCacheRandomMovementPaths" = 0;
                    "ActivateWeather" = 1;
                    "ChangeWeatherInterval" = 600000;
                    "AllowTickets" = 1;
                    "LevelReq.Ticket" = 1;
                    "DeletedCharacterTicketTrace" = 0;
                    "AllowPlayerCommands" = 1;
                    "Command.LookupMaxResults" = 0;
                    "Die.Command.Mode" = 1;
                    "GM.LoginState" = 2;
                    "GM.Visible" = 2;
                    "GM.Chat" = 2;
                    "GM.WhisperingTo" = 2;
                    "GM.InGMList.Level" = 3;
                    "GM.InWhoList.Level" = 3;
                    "GM.StartLevel" = 1;
                    "GM.AllowInvite" = 0;
                    "GM.AllowFriend" = 0;
                    "GM.LowerSecurity" = 0;
                    "GM.TicketSystem.ChanceOfGMSurvey" = 50;
                    "DisableWaterBreath" = 4;
                    "AllFlightPaths" = 0;
                    "InstantFlightPaths" = 0;
                    "AlwaysMaxSkillForLevel" = 0;
                    "AlwaysMaxWeaponSkill" = 0;
                    "PlayerStart.AllReputation" = 0;
                    "PlayerStart.CustomSpells" = 0;
                    "PlayerStart.MapsExplored" = 0;
                    "Trial.LevelCap" = 20;
                    "Trial.MoneyCap" = 100000;
                    "Trial.TradeSkillCap" = 100;
                    "Trial.Restriction.Chat" = 1;
                    "Trial.Restriction.Mail" = 1;
                    "Trial.Restriction.Trade" = 1;
                    "Trial.Restriction.Auction" = 1;
                    "Trial.Restriction.Party" = 1;
                    "Trial.Restriction.Guild" = 1;
                    "Trial.Restriction.Queue" = 1;
                    "PlayerSaveInterval" = 900000;
                    "PlayerSave.Stats.MinLevel" = 0;
                    "PlayerSave.Stats.SaveOnlyOnLogout" = 1;
                    "PlayerSave.AdditionalSaves" = 0;
                    "CleanCharacterDB" = 0;
                    "PersistentCharacterCleanFlags" = 0;
                    "ValidateSkillLearnedBySpells" = 1;
                    "CharDelete.Method" = 0;
                    "CharDelete.MinLevel" = 0;
                    "CharDelete.KeepDays" = 30;
                    "MinPlayerName" = 2;
                    "MinPetName" = 2;
                    "DeclinedNames" = 0;
                    "StrictNames.Reserved" = 1;
                    "StrictNames.Profanity" = 1;
                    "StrictPlayerNames" = 0;
                    "StrictPetNames" = 0;
                    "CharacterCreating.Disabled" = 0;
                    "CharacterCreating.Disabled.RaceMask" = 0;
                    "CharacterCreating.Disabled.ClassMask" = 0;
                    "CharactersPerAccount" = 50;
                    "CharactersPerRealm" = 10;
                    "HeroicCharactersPerRealm" = 1;
                    "CharacterCreating.MinLevelForHeroicCharacter" = 55;
                    "StartPlayerLevel" = 1;
                    "StartHeroicPlayerLevel" = 55;
                    "SkipCinematics" = 0;
                    "StartPlayerMoney" = 0;
                    "StartHeroicPlayerMoney" = 2000;
                    "PlayerStart.String" = "";
                    "EnablePlayerSettings" = 0;
                    "MaxPlayerLevel" = 80;
                    "MinDualSpecLevel" = 40;
                    "WaterBreath.Timer" = 180000;
                    "EnableLowLevelRegenBoost" = 1;
                    "Rate.MoveSpeed.Player" = 1;
                    "Rate.MoveSpeed.NPC" = 1;
                    "Rate.Damage.Fall" = 1;
                    "Rate.Talent" = 1;
                    "Rate.Talent.Pet" = 1;
                    "Rate.Health" = 1;
                    "Rate.Mana" = 1;
                    "Rate.Rage.Income" = 1;
                    "Rate.Rage.Loss" = 1;
                    "Rate.RunicPower.Income" = 1;
                    "Rate.RunicPower.Loss" = 1;
                    "Rate.Focus" = 1;
                    "Rate.Energy" = 1;
                    "Rate.Rest.InGame" = 1;
                    "Rate.Rest.Offline.InTavernOrCity" = 1;
                    "Rate.Rest.Offline.InWilderness" = 1;
                    "Rate.Rest.MaxBonus" = "1.5";
                    "Rate.MissChanceMultiplier.TargetCreature" = 11;
                    "Rate.MissChanceMultiplier.TargetPlayer" = 7;
                    "Rate.MissChanceMultiplier.OnlyAffectsPlayer" = 0;
                    "LevelReq.Trade" = 1;
                    "NoResetTalentsCost" = 0;
                    "ToggleXP.Cost" = 100000;
                    "SpellQueue.Enabled" = 1;
                    "SpellQueue.Window" = 400;
                    "Achievement.RealmFirstKillWindow" = 60;
                    "Achievement.RealmFirstRaceLimitOnePerCharacter" = 1;
                    "MaxPrimaryTradeSkill" = 2;
                    "SkillChance.Prospecting" = 0;
                    "SkillChance.Milling" = 0;
                    "Rate.Skill.Discovery" = 1;
                    "SkillGain.Crafting" = 1;
                    "SkillGain.Defense" = 1;
                    "SkillGain.Gathering" = 1;
                    "SkillGain.Weapon" = 1;
                    "SkillChance.Orange" = 100;
                    "SkillChance.Yellow" = 75;
                    "SkillChance.Green" = 25;
                    "SkillChance.Grey" = 0;
                    "SkillChance.MiningSteps" = 0;
                    "SkillChance.SkinningSteps" = 0;
                    "OffhandCheckAtSpellUnlearn" = 1;
                    "Stats.Limits.Enable" = 0;
                    "Stats.Limits.Dodge" = "95.0";
                    "Stats.Limits.Parry" = "95.0";
                    "Stats.Limits.Block" = "95.0";
                    "Stats.Limits.Crit" = "95.0";
                    "Rate.Reputation.Gain" = 1;
                    "Rate.Reputation.LowLevel.Kill" = 1;
                    "Rate.Reputation.LowLevel.Quest" = 1;
                    "Rate.Reputation.RecruitAFriendBonus" = "0.1";
                    "Rate.Reputation.Gain.WSG" = 1;
                    "Rate.Reputation.Gain.AB" = 1;
                    "Rate.Reputation.Gain.AV" = 1;
                    "MaxGroupXPDistance" = 74;
                    "Rate.XP.Kill" = 1;
                    "Rate.XP.Quest" = 1;
                    "Rate.XP.Quest.DF" = 1;
                    "Rate.XP.Explore" = 1;
                    "Rate.XP.Pet" = 1;
                    "Rate.XP.BattlegroundKillAV" = 1;
                    "Rate.XP.BattlegroundKillWSG" = 1;
                    "Rate.XP.BattlegroundKillAB" = 1;
                    "Rate.XP.BattlegroundKillEOTS" = 1;
                    "Rate.XP.BattlegroundKillSOTA" = 1;
                    "Rate.XP.BattlegroundKillIC" = 1;
                    "Rate.XP.BattlegroundBonus" = 1;
                    "Rate.Pet.LevelXP" = "0.05";
                    "MaxHonorPoints" = 75000;
                    "MaxHonorPointsMoneyPerPoint" = 0;
                    "StartHonorPoints" = 0;
                    "HonorPointsAfterDuel" = 0;
                    "Rate.Honor" = 1;
                    "MaxArenaPoints" = 10000;
                    "StartArenaPoints" = 0;
                    "Arena.LegacyArenaPoints" = 0;
                    "Rate.ArenaPoints" = 1;
                    "Rate.ArenaPoints2v2" = "0.76";
                    "Rate.ArenaPoints3v3" = "0.88";
                    "PvPToken.Enable" = 0;
                    "PvPToken.MapAllowType" = 4;
                    "PvPToken.ItemID" = 29434;
                    "PvPToken.ItemCount" = 1;
                    "DurabilityLoss.InPvP" = 0;
                    "DurabilityLoss.OnDeath" = 10;
                    "DurabilityLoss.OnSpiritResurrect" = 25;
                    "DurabilityLossChance.Damage" = "0.5";
                    "DurabilityLossChance.Absorb" = "0.5";
                    "DurabilityLossChance.Parry" = "0.05";
                    "DurabilityLossChance.Block" = "0.05";
                    "Death.SicknessLevel" = 11;
                    "Death.CorpseReclaimDelay.PvP" = 1;
                    "Death.CorpseReclaimDelay.PvE" = 1;
                    "Death.Bones.World" = 1;
                    "Death.Bones.BattlegroundOrArena" = 1;
                    "Pet.RankMod.Health" = 1;
                    "ItemDelete.Method" = 0;
                    "ItemDelete.Vendor" = 0;
                    "ItemDelete.Quality" = 3;
                    "ItemDelete.ItemLevel" = 80;
                    "ItemDelete.KeepDays" = 0;
                    "DBC.EnforceItemAttributes" = 1;
                    "Rate.Drop.Item.Poor" = 1;
                    "Rate.Drop.Item.Normal" = 1;
                    "Rate.Drop.Item.Uncommon" = 1;
                    "Rate.Drop.Item.Rare" = 1;
                    "Rate.Drop.Item.Epic" = 1;
                    "Rate.Drop.Item.Legendary" = 1;
                    "Rate.Drop.Item.Artifact" = 1;
                    "Rate.Drop.Item.Referenced" = 1;
                    "Rate.Drop.Money" = 1;
                    "Rate.Drop.Item.ReferencedAmount" = 1;
                    "Rate.Drop.Item.GroupAmount" = 1;
                    "LootNeedBeforeGreedILvlRestriction" = 70;
                    "Item.SetItemTradeable" = 1;
                    "Quests.EnableQuestTracker" = 0;
                    "QuestPOI.Enabled" = 1;
                    "Quests.LowLevelHideDiff" = 4;
                    "Quests.HighLevelHideDiff" = 7;
                    "Quests.IgnoreRaid" = 0;
                    "Quests.IgnoreAutoAccept" = 0;
                    "Quests.IgnoreAutoComplete" = 0;
                    "Rate.RewardQuestMoney" = 1;
                    "Rate.RewardBonusMoney" = 1;
                    "MonsterSight" = "50.000000";
                    "Rate.Creature.Aggro" = 1;
                    "CreatureFamilyFleeAssistanceRadius" = 30;
                    "CreatureLeashRadius" = 30;
                    "CreatureFamilyAssistanceRadius" = 10;
                    "CreatureFamilyAssistanceDelay" = 2000;
                    "CreatureFamilyAssistancePeriod" = 3000;
                    "CreatureFamilyFleeDelay" = 7000;
                    "WorldBossLevelDiff" = 3;
                    "Corpse.Decay.NORMAL" = 60;
                    "Corpse.Decay.RARE" = 300;
                    "Corpse.Decay.ELITE" = 300;
                    "Corpse.Decay.RAREELITE" = 300;
                    "Corpse.Decay.WORLDBOSS" = 3600;
                    "Rate.Corpse.Decay.Looted" = "0.5";
                    "Rate.Creature.Normal.Damage" = 1;
                    "Rate.Creature.Elite.Elite.Damage" = 1;
                    "Rate.Creature.Elite.RARE.Damage" = 1;
                    "Rate.Creature.Elite.RAREELITE.Damage" = 1;
                    "Rate.Creature.Elite.WORLDBOSS.Damage" = 1;
                    "Rate.Creature.Normal.SpellDamage" = 1;
                    "Rate.Creature.Elite.Elite.SpellDamage" = 1;
                    "Rate.Creature.Elite.RARE.SpellDamage" = 1;
                    "Rate.Creature.Elite.RAREELITE.SpellDamage" = 1;
                    "Rate.Creature.Elite.WORLDBOSS.SpellDamage" = 1;
                    "Rate.Creature.Normal.HP" = 1;
                    "Rate.Creature.Elite.Elite.HP" = 1;
                    "Rate.Creature.Elite.RARE.HP" = 1;
                    "Rate.Creature.Elite.RAREELITE.HP" = 1;
                    "Rate.Creature.Elite.WORLDBOSS.HP" = 1;
                    "ListenRange.Say" = 40;
                    "ListenRange.TextEmote" = 40;
                    "ListenRange.Yell" = 300;
                    "Creature.RepositionAgainstNpcs" = 1;
                    "Creature.MovingStopTimeForPlayer" = 180000;
                    "WaypointMovementStopTimeForPlayer" = 120;
                    "NpcRegenHPIfTargetIsUnreachable" = 1;
                    "Creature.Instance.TeleportToUnreachableTarget" = 0;
                    "Creatures.CustomIDs" = "190010,55005,999991,25462,98888,601014,34567,34568";
                    "Rate.SellValue.Item.Poor" = 1;
                    "Rate.SellValue.Item.Normal" = 1;
                    "Rate.SellValue.Item.Uncommon" = 1;
                    "Rate.SellValue.Item.Rare" = 1;
                    "Rate.SellValue.Item.Epic" = 1;
                    "Rate.SellValue.Item.Legendary" = 1;
                    "Rate.SellValue.Item.Artifact" = 1;
                    "Rate.SellValue.Item.Heirloom" = 1;
                    "Rate.BuyValue.Item.Poor" = 1;
                    "Rate.BuyValue.Item.Normal" = 1;
                    "Rate.BuyValue.Item.Uncommon" = 1;
                    "Rate.BuyValue.Item.Rare" = 1;
                    "Rate.BuyValue.Item.Epic" = 1;
                    "Rate.BuyValue.Item.Legendary" = 1;
                    "Rate.BuyValue.Item.Artifact" = 1;
                    "Rate.BuyValue.Item.Heirloom" = 1;
                    "Rate.RepairCost" = 1;
                    "LeaveGroupOnLogout.Enabled" = 0;
                    "Group.Raid.LevelRestriction" = 10;
                    "Group.RandomRollMaximum" = 1000000;
                    "Instance.GMSummonPlayer" = 0;
                    "Instance.IgnoreLevel" = 0;
                    "Instance.IgnoreRaid" = 0;
                    "Instance.ResetTimeHour" = 4;
                    "Instance.ResetTimeRelativeTimestamp" = 1135814400;
                    "Rate.InstanceResetTime" = 1;
                    "Instance.UnloadDelay" = 1800000;
                    "AccountInstancesPerHour" = 5;
                    "Instance.SharedNormalHeroicId" = 1;
                    "DungeonAccessRequirements.PrintMode" = 1;
                    "DungeonAccessRequirements.PortalAvgIlevelCheck" = 0;
                    "DungeonAccessRequirements.OptionalStringID" = 0;
                    "CAIS.Enable" = 0;
                    "JoinBGAndLFG.Enable" = 0;
                    "LFG.MailItemOnFullInventory" = 0;
                    "DungeonFinder.OptionsMask" = 5;
                    "LFG.Location.All" = 0;
                    "LFG.MaxKickCount" = 2;
                    "LFG.KickPreventionTimer" = 900;
                    "DungeonAccessRequirements.LFGLevelDBCOverride" = 0;
                    "DungeonFinder.CastDeserter" = 1;
                    "DungeonFinder.AllowCompleted" = 1;
                    "DungeonFinder.DungeonSelectionCooldown" = 0;
                    "MinCharterName" = 2;
                    "StrictCharterNames" = 0;
                    "Guild.EventLogRecordsCount" = 100;
                    "Guild.ResetHour" = 6;
                    "Guild.BankEventLogRecordsCount" = 25;
                    "MinPetitionSigns" = 9;
                    "Guild.CharterCost" = 1000;
                    "Guild.AllowMultipleGuildMaster" = 0;
                    "Guild.BankInitialTabs" = 0;
                    "Guild.BankTabCost0" = 1000000;
                    "Guild.BankTabCost1" = 2500000;
                    "Guild.BankTabCost2" = 5000000;
                    "Guild.BankTabCost3" = 10000000;
                    "Guild.BankTabCost4" = 25000000;
                    "Guild.BankTabCost5" = 50000000;
                    "Guild.MemberLimit" = 0;
                    "FFAPvPTimer" = 30;
                    "OutdoorPvPCaptureRate" = "1.0";
                    "Wintergrasp.Enable" = 1;
                    "Wintergrasp.PlayerMax" = 120;
                    "Wintergrasp.PlayerMin" = 0;
                    "Wintergrasp.PlayerMinLvl" = 75;
                    "Wintergrasp.BattleTimer" = 30;
                    "Wintergrasp.NoBattleTimer" = 150;
                    "Wintergrasp.CrashRestartTimer" = 10;
                    "Wintergrasp.SkipBattleSessionCount" = 3500;
                    "Wintergrasp.KickVoAPlayers" = 1;
                    "Wintergrasp.EssenceBothFactions" = 0;
                    "Wintergrasp.DeferShutdownTimer" = 0;
                    "Battleground.PrepTime" = 120;
                    "Battleground.CastDeserter" = 1;
                    "Battleground.QueueAnnouncer.Enable" = 0;
                    "Battleground.QueueAnnouncer.Limit.MinLevel" = 0;
                    "Battleground.QueueAnnouncer.Limit.MinPlayers" = 3;
                    "Battleground.QueueAnnouncer.SpamProtection.Delay" = 30;
                    "Battleground.QueueAnnouncer.PlayerOnly" = 0;
                    "Battleground.QueueAnnouncer.Timed" = 0;
                    "Battleground.QueueAnnouncer.Timer" = 30000;
                    "Battleground.PrematureFinishTimer" = 300000;
                    "Battleground.PremadeGroupWaitForMatch" = 1800000;
                    "Battleground.GiveXPForKills" = 0;
                    "Battleground.Random.ResetHour" = 6;
                    "Battleground.StoreStatistics.Enable" = 0;
                    "Battleground.TrackDeserters.Enable" = 0;
                    "Battleground.InvitationType" = 0;
                    "Battleground.ReportAFK.Timer" = 4;
                    "Battleground.ReportAFK" = 3;
                    "Battleground.DisableQuestShareInBG" = 0;
                    "Battleground.DisableReadyCheckInBG" = 0;
                    "Battleground.RewardWinnerHonorFirst" = 30;
                    "Battleground.RewardWinnerArenaFirst" = 25;
                    "Battleground.RewardWinnerHonorLast" = 15;
                    "Battleground.RewardWinnerArenaLast" = 0;
                    "Battleground.RewardLoserHonorFirst" = 5;
                    "Battleground.RewardLoserHonorLast" = 5;
                    "Battleground.PlayerRespawn" = 30;
                    "Battleground.RestorationBuffRespawn" = 20;
                    "Battleground.BerserkingBuffRespawn" = 120;
                    "Battleground.SpeedBuffRespawn" = 150;
                    "Battleground.Override.LowLevels.MinPlayers" = 0;
                    "Battleground.Override.LowLevels.MinPlayers.AV" = 0;
                    "Battleground.Override.LowLevels.MinPlayers.WS" = 0;
                    "Battleground.Override.LowLevels.MinPlayers.AB" = 0;
                    "Battleground.Override.LowLevels.MinPlayers.EY" = 0;
                    "Battleground.Override.LowLevels.MinPlayers.SA" = 0;
                    "Battleground.Override.LowLevels.MinPlayers.IC" = 0;
                    "Battleground.Warsong.Flags" = 3;
                    "Battleground.Arathi.CapturePoints" = 1600;
                    "Battleground.Alterac.Reinforcements" = 600;
                    "Battleground.Alterac.ReputationOnBossDeath" = 350;
                    "Battleground.EyeOfTheStorm.CapturePoints" = 1600;
                    "Arena.PrepTime" = 60;
                    "Arena.MaxRatingDifference" = 150;
                    "Arena.RatingDiscardTimer" = 600000;
                    "Arena.PreviousOpponentsDiscardTimer" = 120000;
                    "Arena.AutoDistributePoints" = 0;
                    "Arena.AutoDistributeInterval" = 7;
                    "Arena.GamesRequired" = 10;
                    "Arena.QueueAnnouncer.Enable" = 0;
                    "Arena.QueueAnnouncer.PlayerOnly" = 0;
                    "Arena.QueueAnnouncer.Detail" = 3;
                    "Arena.ArenaStartRating" = 0;
                    "Arena.LegacyArenaStartRating" = 1500;
                    "Arena.ArenaStartPersonalRating" = 0;
                    "Arena.ArenaStartMatchmakerRating" = 1500;
                    "Arena.ArenaWinRatingModifier1" = 48;
                    "Arena.ArenaWinRatingModifier2" = 24;
                    "Arena.ArenaLoseRatingModifier" = 24;
                    "Arena.ArenaMatchmakerRatingModifier" = 24;
                    "ArenaTeam.CharterCost.2v2" = 800000;
                    "ArenaTeam.CharterCost.3v3" = 1200000;
                    "ArenaTeam.CharterCost.5v5" = 2000000;
                    "MaxAllowedMMRDrop" = 500;
                    "MailDeliveryDelay" = 3600;
                    "LevelReq.Mail" = 1;
                    "IsContinentTransport.Enabled" = 1;
                    "IsPreloadedContinentTransport.Enabled" = 0;
                    "StrictChannelNames" = 0;
                    "AddonChannel" = 1;
                    "ChatFakeMessagePreventing" = 1;
                    "ChatStrictLinkChecking.Severity" = 0;
                    "ChatStrictLinkChecking.Kick" = 0;
                    "ChatFlood.MessageCount" = 10;
                    "ChatFlood.MessageDelay" = 1;
                    "ChatFlood.AddonMessageCount" = 100;
                    "ChatFlood.AddonMessageDelay" = 1;
                    "ChatFlood.MuteTime" = 10;
                    "Chat.MuteFirstLogin" = 0;
                    "Chat.MuteTimeFirstLogin" = 120;
                    "Channel.RestrictedLfg" = 1;
                    "Channel.SilentlyGMJoin" = 0;
                    "ChatLevelReq.Channel" = 1;
                    "ChatLevelReq.Whisper" = 1;
                    "ChatLevelReq.Say" = 1;
                    "PartyLevelReq" = 1;
                    "PreserveCustomChannels" = 0;
                    "PreserveCustomChannelDuration" = 14;
                    "ChatFilter.Whisper" = 1;
                    "ChatFilter.Say" = 0;
                    "ChatFilter.Yell" = 0;
                    "ChatFilter.Emote" = 0;
                    "AllowTwoSide.Accounts" = 1;
                    "AllowTwoSide.Interaction.Calendar" = 0;
                    "AllowTwoSide.Interaction.Chat" = 0;
                    "AllowTwoSide.Interaction.Channel" = 0;
                    "AllowTwoSide.Interaction.Group" = 0;
                    "AllowTwoSide.Interaction.Guild" = 0;
                    "AllowTwoSide.Interaction.Arena" = 0;
                    "AllowTwoSide.Interaction.Auction" = 0;
                    "TalentsInspecting" = 1;
                    "ChangeFaction.MaxMoney" = 0;
                    "RecruitAFriend.MaxLevel" = 60;
                    "RecruitAFriend.MaxDifference" = 4;
                    "MaxRecruitAFriendBonusDistance" = 100;
                    "Calendar.DeleteOldEventsHour" = 6;
                    "Event.Announce" = 0;
                    "Sunsreach.CounterMax" = 10000;
                    "ScourgeInvasion.CounterFirst" = 50;
                    "ScourgeInvasion.CounterSecond" = 100;
                    "ScourgeInvasion.CounterThird" = 150;
                    "AuctionHouse.WorkerThreads" = 1;
                    "LevelReq.Auction" = 1;
                    "Rate.Auction.Time" = 1;
                    "Rate.Auction.Deposit" = 1;
                    "Rate.Auction.Cut" = 1;
                    "PlayerDump.DisallowPaths" = 1;
                    "PlayerDump.DisallowOverwrite" = 1;
                    "ICC.Buff.Alliance" = 73828;
                    "ICC.Buff.Horde" = 73822;
                    "WipeGunshipBlizzlike.Enable" = 1;
                    "Minigob.Manabonk.Enable" = 1;
                    "Calculate.Creature.Zone.Area.Data" = 0;
                    "Calculate.Gameoject.Zone.Area.Data" = 0;
                    "DailyRBGArenaPoints.MinLevel" = 71;
                    "MunchingBlizzlike.Enabled" = 1;
                    "Daze.Enabled" = 1;
                    "InfiniteAmmo.Enabled" = 0;
                    "Debug.Battleground" = 0;
                    "Debug.Arena" = 0;
                    "Debug.LFG" = 0;
                    "Respawn.DynamicRateCreature" = 1;
                    "Respawn.DynamicMinimumCreature" = 10;
                    "Respawn.DynamicRateGameObject" = 1;
                    "Respawn.DynamicMinimumGameObject" = 10;
                    "Respawn.DynamicEscortNPC" = 0;
                    "Respawn.ForceCompatibilityMode" = 0;
                    "Cluster.Enabled" = 0;
                    "Cluster.AvailableMaps" = "";
                    "Cluster.IsCrossrealm" = 0;
                }
                //
                # host-dependent values, override the dist literals above
                {
                    "RealmID" = "1";
                    "DataDir" = toString cfg.dataDir;
                    "WorldServerPort" = toString cfg.worldPort;
                    "LoginDatabaseInfo" = dbInfo "acore_auth";
                    "WorldDatabaseInfo" = dbInfo "acore_world";
                    "CharacterDatabaseInfo" = dbInfo "acore_characters";
                    "LogsDir" = logsDir;
                    "TempDir" = tmpDir;
                    "MySQLExecutable" = mysqlExe;
                };

            dbimport =
                # literal defaults from dbimport.conf.dist
                {
                    "LogsDir" = "";
                    "MySQLExecutable" = "";
                    "TempDir" = "";
                    "LoginDatabaseInfo" = "127.0.0.1;3306;acore;acore;acore_auth";
                    "WorldDatabaseInfo" = "127.0.0.1;3306;acore;acore;acore_world";
                    "CharacterDatabaseInfo" = "127.0.0.1;3306;acore;acore;acore_characters";
                    "Database.Reconnect.Seconds" = 5;
                    "Database.Reconnect.Attempts" = 5;
                    "LoginDatabase.WorkerThreads" = 1;
                    "WorldDatabase.WorkerThreads" = 1;
                    "CharacterDatabase.WorkerThreads" = 1;
                    "LoginDatabase.SynchThreads" = 1;
                    "WorldDatabase.SynchThreads" = 1;
                    "CharacterDatabase.SynchThreads" = 1;
                    "Updates.EnableDatabases" = 7;
                    "Updates.AllowedModules" = "all";
                    "Updates.AutoSetup" = 1;
                    "Updates.Redundancy" = 1;
                    "Updates.ArchivedRedundancy" = 0;
                    "Updates.AllowRehash" = 1;
                    "Updates.CleanDeadRefMaxCount" = 3;
                    "Appender.Console" = "1,5,0,\"1 9 3 6 5 8\"";
                    "Appender.DBImport" = "2,5,0,DBImport.log,w";
                    "Logger.root" = "4,Console DBImport";
                }
                //
                # host-dependent values, override the dist literals above
                {
                    "LoginDatabaseInfo" = dbInfo "acore_auth";
                    "WorldDatabaseInfo" = dbInfo "acore_world";
                    "CharacterDatabaseInfo" = dbInfo "acore_characters";
                    "LogsDir" = logsDir;
                    "TempDir" = tmpDir;
                    "MySQLExecutable" = mysqlExe;
                };

        }
;

in
{
    inherit
        confValueType
        renderConf
        defaults;
}
